# Generated by Django 5.2.1 on 2025-05-24 02:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=10)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'db_table': 'accounts_invitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=10)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade_level', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Registration Code',
                'verbose_name_plural': 'Registration Codes',
                'db_table': 'accounts_registration_code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='accounts_us_session_5ce38e_idx'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='registrationcode',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_registration_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationcode',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_codes', to='accounts.school'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email', 'status'], name='accounts_in_email_0582fe_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['token'], name='accounts_in_token_be8e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['expires_at'], name='accounts_in_expires_0319bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['invited_by'], name='accounts_in_invited_1dadce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('email', 'school', 'status')},
        ),
        migrations.AddIndex(
            model_name='registrationcode',
            index=models.Index(fields=['code'], name='accounts_re_code_8a5e54_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationcode',
            index=models.Index(fields=['school', 'status'], name='accounts_re_school__c5c96b_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationcode',
            index=models.Index(fields=['expires_at'], name='accounts_re_expires_a80dc9_idx'),
        ),
    ]
